/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Cylinder = IDL.Record({
  'code' : IDL.Text,
  'capacityKg' : IDL.Float64,
  'tareKg' : IDL.Float64,
  'currentGasKg' : IDL.Float64,
});
export const Time = IDL.Int;
export const GasRecovery = IDL.Record({
  'kg' : IDL.Float64,
  'technician' : IDL.Text,
  'equipment' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
  'gasType' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignCylinder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCylinder' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'createCylinderFull' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'deleteAllCylinders' : IDL.Func([], [], []),
  'deleteCylinder' : IDL.Func([IDL.Text], [], []),
  'exportCylinderCsv' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllAssignments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllCylinders' : IDL.Func([], [IDL.Vec(Cylinder)], ['query']),
  'getAllCylindersByCurrentGas' : IDL.Func([], [IDL.Vec(Cylinder)], ['query']),
  'getCylinder' : IDL.Func([IDL.Text], [Cylinder], ['query']),
  'getCylinderMovements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GasRecovery)],
      ['query'],
    ),
  'registerRecovery' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'registerRecoveryWithTimestamp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Time],
      [],
      [],
    ),
  'returnCylinder' : IDL.Func([IDL.Text], [], []),
  'totalDischarge' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Cylinder = IDL.Record({
    'code' : IDL.Text,
    'capacityKg' : IDL.Float64,
    'tareKg' : IDL.Float64,
    'currentGasKg' : IDL.Float64,
  });
  const Time = IDL.Int;
  const GasRecovery = IDL.Record({
    'kg' : IDL.Float64,
    'technician' : IDL.Text,
    'equipment' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
    'gasType' : IDL.Text,
  });
  
  return IDL.Service({
    'assignCylinder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCylinder' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
    'createCylinderFull' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'deleteAllCylinders' : IDL.Func([], [], []),
    'deleteCylinder' : IDL.Func([IDL.Text], [], []),
    'exportCylinderCsv' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllAssignments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllCylinders' : IDL.Func([], [IDL.Vec(Cylinder)], ['query']),
    'getAllCylindersByCurrentGas' : IDL.Func(
        [],
        [IDL.Vec(Cylinder)],
        ['query'],
      ),
    'getCylinder' : IDL.Func([IDL.Text], [Cylinder], ['query']),
    'getCylinderMovements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GasRecovery)],
        ['query'],
      ),
    'registerRecovery' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'registerRecoveryWithTimestamp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, Time],
        [],
        [],
      ),
    'returnCylinder' : IDL.Func([IDL.Text], [], []),
    'totalDischarge' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };