/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GasRecovery {
    kg: number;
    technician: string;
    equipment: string;
    timestamp: Time;
    location: string;
    gasType: string;
}
export type Time = bigint;
export interface Cylinder {
    code: string;
    capacityKg: number;
    tareKg: number;
    currentGasKg: number;
}
export interface backendInterface {
    assignCylinder(code: string, technician: string): Promise<void>;
    createCylinder(code: string, capacityKg: number, tareKg: number): Promise<void>;
    createCylinderFull(code: string, capacityKg: number, tareKg: number, currentGasKg: number): Promise<void>;
    deleteAllCylinders(): Promise<void>;
    deleteCylinder(code: string): Promise<void>;
    exportCylinderCsv(code: string): Promise<string>;
    getAllAssignments(): Promise<Array<[string, string]>>;
    getAllCylinders(): Promise<Array<Cylinder>>;
    getAllCylindersByCurrentGas(): Promise<Array<Cylinder>>;
    getCylinder(code: string): Promise<Cylinder>;
    getCylinderMovements(code: string): Promise<Array<GasRecovery>>;
    registerRecovery(code: string, location: string, equipment: string, technician: string, gasType: string, kg: number): Promise<void>;
    registerRecoveryWithTimestamp(code: string, location: string, equipment: string, technician: string, gasType: string, kg: number, timestamp: bigint): Promise<void>;
    returnCylinder(code: string): Promise<void>;
    totalDischarge(code: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignCylinder(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCylinder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCylinder(arg0, arg1);
            return result;
        }
    }
    async createCylinder(arg0: string, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCylinder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCylinder(arg0, arg1, arg2);
            return result;
        }
    }
    async createCylinderFull(arg0: string, arg1: number, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCylinderFull(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCylinderFull(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAllCylinders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllCylinders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllCylinders();
            return result;
        }
    }
    async deleteCylinder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCylinder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCylinder(arg0);
            return result;
        }
    }
    async exportCylinderCsv(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCylinderCsv(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCylinderCsv(arg0);
            return result;
        }
    }
    async getAllAssignments(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return result;
        }
    }
    async getAllCylinders(): Promise<Array<Cylinder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCylinders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCylinders();
            return result;
        }
    }
    async getAllCylindersByCurrentGas(): Promise<Array<Cylinder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCylindersByCurrentGas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCylindersByCurrentGas();
            return result;
        }
    }
    async getCylinder(arg0: string): Promise<Cylinder> {
        if (this.processError) {
            try {
                const result = await this.actor.getCylinder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCylinder(arg0);
            return result;
        }
    }
    async getCylinderMovements(arg0: string): Promise<Array<GasRecovery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCylinderMovements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCylinderMovements(arg0);
            return result;
        }
    }
    async registerRecovery(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRecovery(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRecovery(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerRecoveryWithTimestamp(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRecoveryWithTimestamp(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRecoveryWithTimestamp(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async returnCylinder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.returnCylinder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.returnCylinder(arg0);
            return result;
        }
    }
    async totalDischarge(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.totalDischarge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.totalDischarge(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
